Обратная сторона реальности
htmlacademy-react/1806037-what-to-watch-9 pull request #4
Opened 2022-03-01 16:47 UTC by FirstBroRussia

---
:mortar_board: [Обратная сторона реальности](https://up.htmlacademy.ru/react/9/user/1806037/tasks/5)

2022-03-02 21:24 UTC, yulllll requested changes

2022-03-02 21:24 UTC, yulllll commented on project/src/components/movie-page/movie-page.tsx
> +  const inputState: any = useLocation().state;
проваливайся внутрь библиотек и смотри там типизацию, чтобы правильно расставить её у себя

2022-03-02 21:24 UTC, yulllll commented on project/src/components/movie-page/movie-page.tsx
> +              <Link to={AppRoute.AddReview} className="btn film-card__button" state={inputState}>Add review</Link>
тут нет подмены :id на идентификатор фильма

2022-03-02 21:24 UTC, yulllll commented on project/src/components/main/page-content/catalog.tsx
> +  const filmsCatalog: JSX.Element[] = [];
используй map и сразу присваивай в переменную вместо пушей

2022-03-02 21:24 UTC, yulllll commented on project/src/components/main/page-content/film-card-for-catalog-wrap.tsx
> +    setState(videoFilmCardElement);
мы не храним в state разметку - только данные для неё

2022-03-02 21:24 UTC, yulllll commented on project/src/components/main/page-content/film-card-for-catalog-wrap.tsx
> +  return state;
компонент должен возвращать разметку, а не state. если хочется возвращать state, то используй кастомный хук, но тогда не храни в нем разметку

2022-03-02 21:24 UTC, yulllll commented on project/src/components/main/header-film-card/page-header.tsx
> +    <HeaderElement key={null} type={undefined} props={undefined}>
если у тебя нет данных для пропса, то не описывай пропс

2022-03-02 21:24 UTC, yulllll commented on project/src/components/add-review/submit-comment-form.tsx
> +  const [state, setState] = useState(formData);
лучше использовать 2 отдельных useState, чем потом делать деструктуризацию и установку одного из полей

2022-03-02 21:24 UTC, yulllll commented on project/src/components/add-review/submit-comment-form.tsx
> +  const [state, setState] = useState(formData);
например
````
 const [comment, setComment] = useState('');

2022-03-02 22:18 UTC, FirstBroRussia commented on markup/css/main.css
> +}
исправил

2022-03-02 22:18 UTC, FirstBroRussia commented on project/src/fetch/request-to-server.ts
> +/* eslint-disable no-alert */
в моменте

2022-03-02 22:19 UTC, FirstBroRussia commented on project/src/fetch/request-to-server.ts
> +// const authorizationToken = 'T2xpdmVyLmNvbm5lckBnbWFpbC5jb20=';
исправил

2022-03-03 10:19 UTC, FirstBroRussia commented on project/src/components/add-review/add-review.tsx
> +  const {id, name, backgroundImage, posterImage}: any = inputState;
исправил

2022-03-03 10:39 UTC, FirstBroRussia commented on project/src/fetch/request-to-server.ts
> +const requestToServer = async (link: string, optionRequest: objRequest) => await fetch(link, optionRequest);
+

2022-03-03 10:40 UTC, FirstBroRussia commented on project/src/fetch/request-to-server.ts
> +const getPromoFilm: any = async () => {
здесь я пока не разобрался как правильно типизировать, обсудим

2022-03-03 10:41 UTC, FirstBroRussia commented on project/src/fetch/request-to-server.ts
> +    alert('ОШИБКА ЗАПРОСА!!!');
сделал чисто для тестов

2022-03-03 10:41 UTC, FirstBroRussia commented on project/src/fetch/request-to-server.ts
> +export {getPromoFilm, getFilmsList};
да в процессе

2022-03-03 10:41 UTC, FirstBroRussia commented on project/src/pages/main-page.tsx
> +/* eslint-disable no-console */
+

2022-03-03 10:41 UTC, FirstBroRussia commented on project/src/types/types.ts
> +type formDataSubmitType = {
+

2022-03-03 10:42 UTC, FirstBroRussia commented on project/src/index.tsx
> +async function StartApp(): Promise<void> {
+, пока не знаю за IIFE

2022-03-03 10:42 UTC, FirstBroRussia commented on project/src/components/video-player/player-play.tsx
> +  console.log(inputState);
+

2022-03-03 10:43 UTC, FirstBroRussia commented on project/src/components/utils/const.ts
> +  ZERO = 0,
+++

2022-03-03 10:43 UTC, FirstBroRussia commented on project/src/components/movie-page/movie-page.tsx
> +  const inputState: any = useLocation().state;
я понял как получать данные о типе, но не всегда это работает как хотелось бы, обсудим

2022-03-03 10:44 UTC, FirstBroRussia commented on project/src/components/movie-page/movie-page.tsx
> +              <Link to={AppRoute.AddReview} className="btn film-card__button" state={inputState}>Add review</Link>
+++

2022-03-03 10:44 UTC, FirstBroRussia commented on project/src/components/main/page-content/film-card-for-catalog-wrap.tsx
> +    setState(videoFilmCardElement);
+++

2022-03-03 10:44 UTC, FirstBroRussia commented on project/src/components/main/page-content/film-card-for-catalog-wrap.tsx
> +  return state;
+++

2022-03-03 10:44 UTC, FirstBroRussia commented on project/src/components/main/header-film-card/page-header.tsx
> +    <HeaderElement key={null} type={undefined} props={undefined}>
линтер ругается если не описаны эти пропсы, поэтому это итог автоисправления

2022-03-03 10:45 UTC, FirstBroRussia commented on project/src/components/add-review/submit-comment-form.tsx
> +  const [state, setState] = useState(formData);
ладно, но в данном контексте не согласен

2022-03-03 11:11 UTC, FirstBroRussia commented on project/src/components/utils/utils.tsx
> +  if (RatingLevelCountValue.ZERO <= ratingCount && ratingCount < RatingLevelCountValue.THREE) {
обсудим

2022-03-03 15:37 UTC, merged